/*CREATE DATABASE itis_sem_webapp;*/

USE itis_sem_webapp;

DROP TABLE IF EXISTS `users`;
CREATE TABLE `users` (
  `USER_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `FIRSTNAME` VARCHAR(20) NOT NULL,
  `LASTNAME` VARCHAR(20) NOT NULL,
   `AGE` INT(10) NOT NULL,
  PRIMARY KEY (`USER_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS  `orders`;
CREATE TABLE `orders` (
	`ORDER_ID` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `USER_ID` INT(10) UNSIGNED NOT NULL,
    `PRODUCT` nvarchar(255) not NULL,
    `PRICE` int(100) not NULL,
    PRIMARY KEY (`ORDER_ID`) USING BTREE,
    FOREIGN KEY (`USER_ID`) references users(`USER_ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;